apiVersion: apps/v1
kind: Deployment
metadata:
  name: bk-website
  labels:
    app: bk-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bk-website
  template:
    metadata:
      labels:
        app: bk-website
    spec:
      containers:
        - name: bk-website
          image: ${ACR_NAME}.azurecr.io/bk-website:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
